"""Every text the desktop UI shows, in one place.

The code keeps English source strings as keys, so logic, tests and stored
data stay language-neutral.  ``tr`` looks up the Swedish text; a string with
no entry is shown as it is, which keeps model names, file names and user
data untouched.  English is the source language, so it needs no table.

The language is chosen in Settings and stored in ``arqen.json``; it is set
with ``set_language`` once at startup, before any window is built.
"""

from __future__ import annotations

# The languages the UI can show, by code, each named in its own language.
LANGUAGES = {"sv": "Svenska", "en": "English"}
DEFAULT_LANGUAGE = "en"
LANGUAGE = DEFAULT_LANGUAGE


def set_language(code: str) -> str:
    """Use ``code`` for all UI text from now on; an unknown code means the default."""
    global LANGUAGE
    LANGUAGE = code if code in LANGUAGES else DEFAULT_LANGUAGE
    return LANGUAGE


def language_name() -> str:
    """The current language named in English, for instructions to the model."""
    return {"sv": "Swedish", "en": "English"}[LANGUAGE]


_SV: dict[str, str] = {
    # Navigation
    "Dashboard": "Översikt",
    "Chat": "Chatt",
    "Mission Control": "Kontrollrum",
    "Agents": "Agenter",
    "Activity": "Aktivitet",
    "Memory": "Minne",
    "Tools": "Verktyg",
    "Tasks": "Uppgifter",
    "Workflows": "Arbetsflöden",
    "Schedules": "Scheman",
    "Content": "Innehåll",
    "Connections": "Anslutningar",
    "CONNECTIONS": "ANSLUTNINGAR",
    "Give an agent access to a package of tools. More integrations are coming.":
        "Ge en agent tillgång till ett paket verktyg. Fler integrationer kommer.",
    "Search connections...": "Sök anslutningar...",
    "No agents yet. Create one under Agents.": "Inga agenter än. Skapa en under Agenter.",
    "{agent} can use {count} of {total} tools.": "{agent} kan använda {count} av {total} verktyg.",
    "{agent} has no tools and can only answer in text.": "{agent} har inga verktyg och kan bara svara med text.",
    "No connections match the search.": "Inga anslutningar matchar sökningen.",
    "BUILT-IN": "INBYGGT",
    "CONNECTED": "ANSLUTEN",
    "All {count} tools": "Alla {count} verktyg",
    "{count} of {total} tools": "{count} av {total} verktyg",
    "GIVE {agent} ACCESS": "GE {agent} TILLGÅNG",
    "GIVE ALL": "GE ALLA",
    "REMOVE": "TA BORT",
    "NOT CONNECTED": "EJ ANSLUTEN",
    "PAUSED": "PAUSAD",
    "MANAGE": "HANTERA",
    "+ CONNECT": "+ ANSLUT",
    "{name} – connection": "{name} – anslutning",
    "Notify here when tasks finish or fail": "Avisera här när uppgifter blir klara eller misslyckas",
    "Pause the connection (agents cannot use it)": "Pausa anslutningen (agenter kan inte använda den)",
    "Fill in every field first.": "Fyll i alla fält först.",
    "Works: {reached}": "Fungerar: {reached}",
    "Did not work: {error}": "Fungerade inte: {error}",
    "Disconnect": "Koppla från",
    "Remove the saved credentials for {name}?": "Ta bort de sparade uppgifterna för {name}?",
    "DISCONNECT": "KOPPLA FRÅN",
    "SIGN IN WITH {name}": "LOGGA IN MED {name}",
    "Arqen (the chat)": "Arqen (chatten)",
    "Tool costs in this log: {total} over {count} paid calls": "Verktygskostnad i loggen: {total} för {count} betalda anrop",
    "FETCH CHAT ID": "HÄMTA CHATT-ID",
    "Which chat should Arqen use?": "Vilken chatt ska Arqen använda?",
    "Filled in: {value}. Press TEST CONNECTION and SAVE.": "Ifyllt: {value}. Tryck TESTA ANSLUTNING och SPARA.",
    "No messages to the bot yet. Write something to it in Telegram and try again. If another program reads the bot (e.g. monitoring), use @userinfobot instead.":
        "Inga meddelanden till boten än. Skriv något till den i Telegram och försök igen. Läser ett annat program av boten (t.ex. övervakning) – använd @userinfobot i stället.",
    "NEEDS RECONNECTING": "BEHÖVER ÅTERANSLUTAS",
    "RECONNECT": "ÅTERANSLUT",
    "The sign-in has expired or was revoked. Press {button} again.":
        "Inloggningen har gått ut eller återkallats. Tryck {button} igen.",
    "{count} connections need to be signed in again.": "{count} anslutningar behöver loggas in igen.",
    "A connection needs to be signed in again.": "En anslutning behöver loggas in igen.",
    "Sign in first.": "Logga in först.",
    "Signed in as {account}.": "Inloggad som {account}.",
    "Signed in.": "Inloggad.",
    "Not signed in. Fill in the client and press {button}.": "Inte inloggad. Fyll i klienten och tryck {button}.",
    "The browser opens {name}. Approve the access there; Arqen waits here.":
        "Webbläsaren öppnar {name}. Godkänn åtkomsten där och stäng inte den här rutan – Arqen sparar själv när du är inloggad (väntar högst 5 minuter).",
    "Connected. The tools can be used now.": "Ansluten. Verktygen kan användas nu.",
    "Connected, but without access to: {scopes}. Those tools will fail until you sign in again and tick them.":
        "Ansluten, men utan åtkomst till: {scopes}. De verktygen fungerar inte förrän du loggar in igen och kryssar i dem.",
    "Open the setup page for {name}": "Öppna inställningssidan för {name}",
    "Arqen is connected to Google": "Arqen är anslutet till Google",
    "The sign-in did not go through": "Inloggningen gick inte igenom",
    "You can close this tab and go back to Arqen.": "Du kan stänga fliken och gå tillbaka till Arqen.",
    "Go back to Arqen and try again.": "Gå tillbaka till Arqen och försök igen.",
    "+ MCP SERVER": "+ MCP-SERVER",
    "Connect an MCP server: its tools become Arqen tools.": "Anslut en MCP-server: dess verktyg blir Arqen-verktyg.",
    "No tools fetched yet.": "Inga verktyg hämtade än.",
    "MCP server": "MCP-server",
    "An MCP server gives Arqen more tools. Its tools ask for approval unless the server marks them as read-only.":
        "En MCP-server ger Arqen fler verktyg. De kräver godkännande, utom de som servern märker som endast läsande.",
    "e.g. Zapier": "t.ex. Zapier",
    "Address (HTTP)": "Adress (HTTP)",
    "Local program": "Lokalt program",
    "Type": "Typ",
    "Address": "Adress",
    "Only if the server asks for one": "Bara om servern kräver det",
    "Token (optional)": "Token (valfri)",
    "Program": "Program",
    "Arguments": "Argument",
    "A local program runs on this computer with your permissions. Only add programs you trust.":
        "Ett lokalt program körs på den här datorn med dina behörigheter. Lägg bara till program du litar på.",
    "Fill in a name and an address or program first.": "Fyll i namn och adress eller program först.",
    "Works: {count} tools ({read_only} read-only).": "Fungerar: {count} verktyg ({read_only} endast läsande).",
    "Remove server": "Ta bort server",
    "Remove {name} and its tools from Arqen?": "Ta bort {name} och dess verktyg från Arqen?",
    "TEST AND FETCH TOOLS": "TESTA OCH HÄMTA VERKTYG",
    "REMOVE SERVER": "TA BORT SERVER",
    "Done: {title}{who}": "✅ Klar: {title}{who}",
    "Failed: {title}{who} – {error}": "⚠️ Misslyckades: {title}{who} – {error}",
    "Settings": "Inställningar",
    "OVERVIEW": "ÖVERSIKT",
    "SYSTEM": "SYSTEM",
    "OPERATIONS": "DRIFT",
    # Chat
    "CHATS": "CHATTAR",
    "NEW CHAT": "NY CHATT",
    "Right-click to open, rename or delete. F2 renames, Delete removes.":
        "Högerklicka för att öppna, byta namn eller ta bort. F2 byter namn, Delete tar bort.",
    "Open": "Öppna",
    "Conversation will appear here...": "Konversationen visas här...",
    "Type a message... (Shift+Enter for a new line)": "Skriv ett meddelande... (Shift+Enter för ny rad)",
    "Send": "Skicka",
    "Stop": "Stoppa",
    "CONFIRM": "BEKRÄFTA",
    "CANCEL": "AVBRYT",
    "Rename": "Byt namn",
    "Delete": "Ta bort",
    "New chat": "Ny chatt",
    "Title:": "Titel:",
    "New name:": "Nytt namn:",
    "Delete chat": "Ta bort chatt",
    "Delete '{title}'?": "Ta bort '{title}'?",
    "YOU": "DU",
    "TOOL": "VERKTYG",
    "TOOL RESULT": "VERKTYGSRESULTAT",
    "ERROR": "FEL",
    # Status line
    "READY": "REDO",
    "READY // RESPONSE COMPLETE": "REDO // SVAR KLART",
    "READY // NEW SESSION": "REDO // NY CHATT",
    "READY // SESSION LOADED": "REDO // CHATT LADDAD",
    "READY // CONFIRMATION CANCELLED": "REDO // BEKRÄFTELSE AVBRUTEN",
    "READY // CONFIRMATION RESOLVED": "REDO // BEKRÄFTELSE KLAR",
    "READY // PROVIDER UPDATED": "REDO // LEVERANTÖR UPPDATERAD",
    "ERROR // REQUEST FAILED": "FEL // FÖRFRÅGAN MISSLYCKADES",
    "ERROR // CONFIRMATION FAILED": "FEL // BEKRÄFTELSEN MISSLYCKADES",
    "STOPPED // RESPONSE DISCARDED": "STOPPAD // SVARET KASTADES",
    "WORKING // PROCESSING REQUEST": "ARBETAR // BEHANDLAR FÖRFRÅGAN",
    "WORKING // RUNNING CONFIRMED TOOL": "ARBETAR // KÖR BEKRÄFTAT VERKTYG",
    "VOICE // ENABLED": "RÖST // PÅ",
    "VOICE // DISABLED": "RÖST // AV",
    "TOOL // {name}": "VERKTYG // {name}",
    "CHAT // {name}": "CHATT // {name}",
    "CONFIRMATION REQUIRED // {name}": "BEKRÄFTELSE KRÄVS // {name}",
    "PROFILE": "PROFIL",
    "FALLBACK": "RESERV",
    "LOCAL - OLLAMA": "LOKAL - OLLAMA",
    "FAST": "SNABB",
    "IMPORTANT": "VIKTIGT",
    "CREATIVE": "KREATIV",
    "PRIVATE": "PRIVAT",
    "CUSTOM": "ANPASSAD",
    # Microphone status parts ("MIC // RECORDING")
    "MIC": "MIKROFON",
    "RECORDING": "SPELAR IN",
    "STOPPING": "STOPPAR",
    "EMPTY": "INGET LJUD",
    "TOO SHORT": "FÖR KORT",
    "LOADING MODEL": "LADDAR MODELL",
    "DECODING": "TOLKAR TAL",
    "NO SPEECH": "INGET TAL",
    # Voice panel
    "IDLE": "VILA",
    "LISTENING": "LYSSNAR",
    "THINKING": "TÄNKER",
    "SPEAKING": "PRATAR",
    "ONLINE": "ONLINE",
    "ARQEN VOICE": "ARQEN RÖST",
    "ARQEN STATS": "ARQEN STATISTIK",
    "🎙 MIC": "🎙 MIKROFON",
    "● REC": "● SPELAR IN",
    "🔊 VOICE": "🔊 RÖST",
    "🔇 VOICE": "🔇 RÖST",
    "Start microphone recording": "Starta inspelning",
    "Stop microphone recording": "Stoppa inspelning",
    "Turn spoken replies on": "Slå på upplästa svar",
    "Turn spoken replies off": "Stäng av upplästa svar",
    "Start/stop microphone recording": "Starta eller stoppa inspelning",
    "Toggle voice mode": "Slå på eller av röstläge",
    # Stats panel
    "THIS CHAT": "DENNA CHATT",
    "tokens": "tokens",
    "in": "in",
    "out": "ut",
    "LATEST RESPONSE": "SENASTE SVAR",
    "time": "tid",
    "cost": "kostnad",
    "TOTAL": "TOTALT",
    # Dashboard
    "DASHBOARD": "ÖVERSIKT",
    "Mission Control // system overview": "Arqen // systemöversikt",
    "AGENTS": "AGENTER",
    "ACTIVE TASKS": "AKTIVA UPPGIFTER",
    "APPROVALS": "GODKÄNNANDEN",
    "WORKFLOW RUNS": "KÖRNINGAR",
    "LATEST ACTIVITY": "SENASTE AKTIVITET",
    "LVL {level}": "NIVÅ {level}",
    "Projects": "Projekt",
    "ADD": "LÄGG TILL",
    "PROJECTS": "PROJEKT",
    "No projects yet. Add them under Projects.": "Inga projekt än. Lägg till dem under Projekt.",
    "Next: {milestone}": "Nästa: {milestone}",
    "All milestones done": "Alla delmål klara",
    "Milestones and how far each project has come": "Delmål och hur långt varje projekt har kommit",
    "+ PROJECT": "+ PROJEKT",
    "Set by hand": "Sätt för hand",
    "MILESTONES": "DELMÅL",
    "New milestone": "Nytt delmål",
    "LATER (not counted)": "SENARE (räknas inte)",
    "Park an idea": "Parkera en idé",
    "PARK": "PARKERA",
    "MAKE MILESTONE": "GÖR TILL DELMÅL",
    "Done {date}": "Klart {date}",
    "New project": "Nytt projekt",
    "Project name:": "Projektets namn:",
    "Remove project": "Ta bort projekt",
    "Remove {name} and its milestones?": "Ta bort {name} och dess delmål?",
    "{n} weeks": "{n} veckor",
    "1 week": "1 vecka",
    "{total} XP  //  {next} to level {level}": "{total} XP  //  {next} kvar till nivå {level}",
    "OPEN ARQEN CHAT": "ÖPPNA ARQEN-CHATTEN",
    "This view will be expanded in the next UI step.": "Den här vyn byggs ut i ett senare steg.",
    "No recent activity": "Ingen aktivitet ännu",
    # Tasks
    "TASKS": "UPPGIFTER",
    "Monitor, run and retry agent work.": "Övervaka, kör och försök igen med agenternas arbete.",
    "ALL TASKS": "ALLA UPPGIFTER",
    "NEEDS ATTENTION": "KRÄVER ÅTGÄRD",
    "Select a task to view its summary and event history.": "Välj en uppgift för att se sammanfattning och händelsehistorik.",
    "Select a task to view status and events.": "Välj en uppgift för att se status och händelser.",
    "OPEN FULL RESULT": "ÖPPNA HELA RESULTATET",
    "PENDING APPROVALS": "VÄNTANDE GODKÄNNANDEN",
    "NEW TASK": "NY UPPGIFT",
    "RUN SELECTED TASK": "KÖR VALD UPPGIFT",
    "RETRY": "FÖRSÖK IGEN",
    "DELETE TASK": "TA BORT UPPGIFT",
    "APPROVE": "GODKÄNN",
    "APPROVAL REQUIRED": "GODKÄNNANDE KRÄVS",
    "Arqen in chat": "Arqen i chatten",
    "+{count} more": "+{count} till",
    "REJECT": "AVVISA",
    "Arqen default": "Arqen (standard)",
    "No agent (Arqen default)": "Ingen agent (Arqen standard)",
    "New Mission Control task": "Ny uppgift",
    "Task:": "Uppgift:",
    "Agent:": "Agent:",
    "Delete task": "Ta bort uppgift",
    "Tasks waiting for approval cannot be deleted.": "Uppgifter som väntar på godkännande kan inte tas bort.",
    "The active model call may take a short moment to stop.": "Det pågående modellanropet kan ta en kort stund att stoppa.",
    "This removes it from Mission Control.": "Den tas bort från kontrollrummet.",
    "Delete '{title}'?\n\n{warning}": "Ta bort '{title}'?\n\n{warning}",
    "The task has reached its maximum attempts.": "Uppgiften har nått sitt max antal försök.",
    "{title}\nStatus: RUNNING\n\nArqen is working...": "{title}\nStatus: KÖRS\n\nArqen arbetar...",
    "Result — {title}": "Resultat — {title}",
    "CLOSE": "STÄNG",
    "STATUS": "STATUS",
    "AGENT": "AGENT",
    "SOURCE": "KÄLLA",
    "ATTEMPTS": "FÖRSÖK",
    "INSTRUCTION": "INSTRUKTION",
    "RESULT": "RESULTAT",
    "EVENT HISTORY": "HÄNDELSEHISTORIK",
    "none": "inget",
    "manual": "manuell",
    "No result stored.": "Inget resultat sparat.",
    "Not available yet.": "Inte tillgängligt än.",
    "task {id}": "uppgift {id}",
    "Approval\nAction: {action}\nTask: {task}\nStatus: {status}": "Godkännande\nÅtgärd: {action}\nUppgift: {task}\nStatus: {status}",
    # Stored event messages
    "Task created": "Uppgift skapad",
    "Task started": "Uppgift startad",
    "Task completed": "Uppgift klar",
    "Task timed out after 15 minutes.": "Uppgiften avbröts efter 15 minuter.",
    "Task is waiting for approval.": "Uppgiften väntar på godkännande.",
    "Task cancelled after the rejection.": "Uppgiften avbröts efter avslaget.",
    "Task recovered after a timeout.": "Uppgiften återställdes efter en timeout.",
    # Mission errors
    "The task is not waiting for an approval.": "Uppgiften väntar inte på något godkännande.",
    "The approval is still waiting for a decision.": "Godkännandet väntar fortfarande på beslut.",
    "The agent '{name}' does not exist.": "Agenten '{name}' finns inte.",
    "The agent '{name}' is inactive.": "Agenten '{name}' är inaktiv.",
    "No runtime is configured for the agent '{name}'.": "Ingen körmiljö är konfigurerad för agenten '{name}'.",
    "The workflow run cannot be resumed.": "Arbetsflödet kan inte återupptas.",
    # Workflows
    "WORKFLOWS": "ARBETSFLÖDEN",
    "Build and run multi-agent pipelines.": "Bygg och kör flöden med flera agenter.",
    "AVAILABLE WORKFLOWS": "TILLGÄNGLIGA ARBETSFLÖDEN",
    "RECENT RUNS": "SENASTE KÖRNINGAR",
    "Select a workflow run to view its results.": "Välj en körning för att se resultatet.",
    "NEW WORKFLOW": "NYTT ARBETSFLÖDE",
    "RUN WORKFLOW": "KÖR ARBETSFLÖDE",
    "RESUME RUN": "ÅTERUPPTA KÖRNING",
    "Status: {status}\nNo results yet.": "Status: {status}\nInga resultat än.",
    "Completed steps: {count}": "Klara steg: {count}",
    "STEP {index}": "STEG {index}",
    "{count} steps  ·  multi-agent pipeline": "{count} steg  ·  flöde med flera agenter",
    "{status}  ·  step {step}": "{status}  ·  steg {step}",
    "No results yet": "Inga resultat än",
    "New workflow": "Nytt arbetsflöde",
    "Name:": "Namn:",
    "One step per line: name | prompt | agent-id (optional)": "Ett steg per rad: namn | instruktion | agent-id (valfritt)",
    "At least one valid step is required.": "Minst ett giltigt steg krävs.",
    "Run workflow": "Kör arbetsflöde",
    "Topic:": "Ämne:",
    "Target audience (optional):": "Målgrupp (valfritt):",
    "Content format (optional):": "Format (valfritt):",
    "YouTube video": "YouTube-video",
    # Schedules
    "SCHEDULES": "SCHEMAN",
    "Automate recurring tasks and workflows.": "Automatisera återkommande uppgifter och arbetsflöden.",
    "NEW SCHEDULE": "NYTT SCHEMA",
    "ENABLE/DISABLE": "AKTIVERA/INAKTIVERA",
    "DELETE SCHEDULE": "TA BORT SCHEMA",
    "ON": "PÅ",
    "OFF": "AV",
    "workflow: {name}": "arbetsflöde: {name}",
    "task: {name}": "uppgift: {name}",
    "{count} tasks": "{count} uppgifter",
    "last: {last}": "senast: {last}",
    "Last run: {last}": "Senaste körning: {last}",
    "One time: {when}": "En gång: {when}",
    "not set": "inte angivet",
    "Advanced: {cron}": "Avancerat: {cron}",
    "Every day at {time}": "Varje dag kl. {time}",
    "Every {day} at {time}": "Varje {day} kl. {time}",
    "Monthly on day {day} at {time}": "Varje månad den {day} kl. {time}",
    "Monday": "måndag",
    "Tuesday": "tisdag",
    "Wednesday": "onsdag",
    "Thursday": "torsdag",
    "Friday": "fredag",
    "Saturday": "lördag",
    "Sunday": "söndag",
    "New schedule": "Nytt schema",
    "e.g. Morning research": "t.ex. Morgonresearch",
    "Name": "Namn",
    "Describe what should happen when this schedule runs.": "Beskriv vad som ska hända när schemat körs.",
    "Instruction": "Instruktion",
    "A regular task": "En vanlig uppgift",
    "Workflow: {name}": "Arbetsflöde: {name}",
    "Run": "Kör",
    "Agent": "Agent",
    "Every day": "Varje dag",
    "Every week": "Varje vecka",
    "Every month": "Varje månad",
    "One time": "En gång",
    "Advanced (cron)": "Avancerat (cron)",
    "When": "När",
    "Weekday": "Veckodag",
    "Time": "Tid",
    "Choose a simple schedule. Advanced cron is optional.": "Välj ett enkelt schema. Avancerad cron är valfritt.",
    "Used only for weekly schedules.": "Används bara för veckoscheman.",
    "Fill in both a name and an instruction.": "Fyll i både namn och instruktion.",
    "Use HH:MM or an ISO-8601 date and time.": "Använd HH:MM eller datum och tid enligt ISO-8601.",
    "Time must use HH:MM, for example 08:00.": "Tiden ska anges som HH:MM, till exempel 08:00.",
    "Delete schedule": "Ta bort schema",
    "Delete '{name}'? Existing tasks will be kept.": "Ta bort '{name}'? Befintliga uppgifter sparas.",
    # Agents
    "Manage runtimes, tools and approval policies.": "Hantera körmiljöer, verktyg och regler för godkännande.",
    "RESEARCH": "UTFORSKNING",
    "PRODUCTION": "PRODUKTION",
    "DISTRIBUTION & REVIEW": "DISTRIBUTION & GRANSKNING",
    "NEW AGENT": "NY AGENT",
    "EDIT": "REDIGERA",
    "ENABLED": "AKTIV",
    "DISABLED": "INAKTIV",
    "CHAT": "CHATTA",
    "{runtime} runtime  ·  {count} tools": "körmiljö {runtime}  ·  {count} verktyg",
    "{detail}\nAllowed tools: {tools}\nRequires approval: {approvals}": "{detail}\nTillåtna verktyg: {tools}\nKräver godkännande: {approvals}",
    "no tools": "inga verktyg",
    "New agent": "Ny agent",
    "ID:": "ID:",
    "Role:": "Roll:",
    "Runtime:": "Körmiljö:",
    "New agent — Allowed tools": "Ny agent — tillåtna verktyg",
    "Select tools by entering their names, separated by commas.": "Välj verktyg genom att skriva deras namn, separerade med kommatecken.",
    "Allowed tools": "Tillåtna verktyg",
    "e.g. system_status,current_time": "t.ex. system_status,current_time",
    "Unknown tools: {tools}": "Okända verktyg: {tools}",
    "Tools requiring approval (comma-separated):": "Verktyg som kräver godkännande (kommaseparerade):",
    "Approval tools must be included in the allowlist.": "Verktyg som kräver godkännande måste också vara tillåtna.",
    "Edit agent": "Redigera agent",
    "Allowed tools:": "Tillåtna verktyg:",
    "Tools requiring approval:": "Verktyg som kräver godkännande:",
    # Activity, memory, tools, content
    "ACTIVITY": "AKTIVITET",
    "Live system events and agent activity.": "Systemhändelser och agentaktivitet i realtid.",
    "MEMORY": "MINNE",
    "User-approved long-term context.": "Långtidsminne som du har godkänt.",
    "REFRESH MEMORY": "UPPDATERA MINNET",
    "SUGGESTIONS TO REVIEW": "FÖRSLAG ATT GRANSKA",
    "APPROVED MEMORIES": "GODKÄNDA MINNEN",
    "{approved} approved  ·  {proposed} suggested  ·  {obsolete} obsolete":
        "Godkända: {approved}  ·  Förslag: {proposed}  ·  Föråldrade: {obsolete}",
    "Suggested by Arqen": "Föreslaget av Arqen",
    "Suggested after reflection": "Föreslaget efter reflektion",
    "REFLECT": "REFLEKTERA",
    "Arqen reads recent tasks and chats and suggests lasting lessons. Costs one model call.":
        "Arqen läser senaste uppgifter och chattar och föreslår bestående lärdomar. Kostar ett modellanrop.",
    "Reflecting on recent tasks and chats...": "Reflekterar över senaste uppgifter och chattar...",
    "Nothing to reflect on yet: no tasks or chats.": "Inget att reflektera över än: inga uppgifter eller chattar.",
    "Arqen found one new suggestion. Review it below.": "Arqen hittade ett nytt förslag. Granska det nedan.",
    "Arqen found {count} new suggestions. Review them below.":
        "Arqen hittade {count} nya förslag. Granska dem nedan.",
    "No new lessons this time.": "Inga nya lärdomar den här gången.",
    "Reflection failed: {error}": "Reflektionen misslyckades: {error}",
    "Suggested": "Föreslaget",
    "obsolete": "föråldrad",
    "MARK OBSOLETE": "MARKERA FÖRÅLDRAD",
    "RESTORE": "ÅTERSTÄLL",
    'Nothing approved yet. Say "remember that ..." or approve a suggestion.':
        'Inget godkänt än. Säg "kom ihåg att ..." eller godkänn ett förslag.',
    "DELETE": "TA BORT",
    "Edit memory": "Redigera minne",
    "Memory:": "Minne:",
    "Delete memory": "Ta bort minne",
    "Delete this memory?": "Ta bort det här minnet?",
    "TOOL GATEWAY": "VERKTYG",
    "Catalog, policies and recent audit activity.": "Katalog, regler och senaste granskningslogg.",
    "REFRESH TOOL GATEWAY": "UPPDATERA VERKTYG",
    "POLICY {agent}: {tools}": "REGEL {agent}: {tools}",
    "all": "alla",
    "AUDIT {status}: {tool} ({time})": "LOGG {status}: {tool} ({time})",
    "CATALOG": "KATALOG",
    "LOG": "LOGG",
    "Search tools...": "Sök verktyg...",
    "SHOW ALL": "VISA ALLA",
    "HIDE ALL": "DÖLJ ALLA",
    "{count} require approval": "{count} kräver godkännande",
    "No agent uses these": "Ingen agent använder dessa",
    "REQUIRES APPROVAL": "KRÄVER GODKÄNNANDE",
    "{count} tools  ·  {approval} require approval": "{count} verktyg  ·  {approval} kräver godkännande",
    "APPROVAL": "GODKÄNNANDE",
    "Used by: {agents}": "Används av: {agents}",
    "all agents": "alla agenter",
    "No tools match the search.": "Inga verktyg matchar sökningen.",
    "{count} tools": "{count} verktyg",
    "Requires approval: {tools}": "Kräver godkännande: {tools}",
    "No tool calls logged yet.": "Inga verktygsanrop loggade än.",
    "audit:ok": "OK",
    "audit:failed": "MISSLYCKAD",
    "audit:approval": "VÄNTAR",
    "CONTENT": "INNEHÅLL",
    "Generated files and workflow artifacts.": "Genererade filer och resultat från arbetsflöden.",
    "REFRESH CONTENT": "UPPDATERA INNEHÅLL",
    # Mission Control overview
    "MISSION CONTROL": "KONTROLLRUM",
    "Operational queue // decide what should happen next.": "Operativ kö // bestäm vad som ska hända härnäst.",
    "TASK QUEUE": "UPPGIFTSKÖ",
    "WAITING APPROVAL": "VÄNTAR PÅ GODKÄNNANDE",
    "ACTIVE WORKFLOWS": "AKTIVA ARBETSFLÖDEN",
    "OPEN TASKS": "ÖPPNA UPPGIFTER",
    "OPEN WORKFLOWS": "ÖPPNA ARBETSFLÖDEN",
    "OPEN ACTIVITY": "ÖPPNA AKTIVITET",
    # Settings
    "Arqen Settings": "Arqen-inställningar",
    "Profile": "Profil",
    "Provider": "Leverantör",
    "Fallback": "Reserv",
    "Local Ollama": "Lokal Ollama",
    "Private – Ollama": "Privat – Ollama",
    "Fast – OpenRouter": "Snabb – OpenRouter",
    "Important – OpenAI": "Viktigt – OpenAI",
    "Creative – Gemini": "Kreativt – Gemini",
    "Description": "Beskrivning",
    "Local and private. Uses Ollama without cloud fallback.": "Lokal och privat. Använder Ollama utan reserv i molnet.",
    "Fast everyday profile. Uses OpenRouter without automatic fallback.": "Snabb vardagsprofil. Använder OpenRouter utan automatisk reserv.",
    "For important tasks. Uses OpenAI without automatic fallback.": "För viktiga uppgifter. Använder OpenAI utan automatisk reserv.",
    "For ideas, writing and creative workflows via Gemini.": "För idéer, skrivande och kreativa flöden via Gemini.",
    "Search models...": "Sök modeller...",
    "Search models": "Sök modell",
    "Model": "Modell",
    "API key": "API-nyckel",
    "Timeout": "Tidsgräns (s)",
    "Enable fallback on provider error": "Använd reserv vid leverantörsfel",
    "Fallback provider": "Reservleverantör",
    "Fallback timeout (s)": "Reservens tidsgräns (s)",
    "Provider status": "Leverantörsstatus",
    "VIEW PROVIDER STATISTICS": "VISA LEVERANTÖRSSTATISTIK",
    "RESET STATISTICS": "NOLLSTÄLL STATISTIK",
    "APPLY PROFILE": "TILLÄMPA PROFIL",
    "Workspace": "Arbetsyta",
    "Statistics": "Statistik",
    "BROWSE FOLDER": "VÄLJ MAPP",
    "About": "Om",
    "The folder Arqen reads and writes files in. It only affects tools — settings, chats and memory remain inside the application ({root}). Leave it empty to use the application folder.":
        "Mappen där Arqen läser och skriver filer. Den påverkar bara verktygen — inställningar, chattar och minne ligger kvar i programmet ({root}). Lämna tomt för att använda programmets egen mapp.",
    "FETCH MODELS": "HÄMTA MODELLER",
    "TEST CONNECTION": "TESTA ANSLUTNING",
    "SAVE": "SPARA",
    "unknown model": "okänd modell",
    "enabled, not used yet": "på, inte använd än",
    "disabled": "av",
    "currently used": "används nu",
    "not enabled": "inte påslagen",
    "no measurement yet": "ingen mätning än",
    "Active: {provider} / {model}\nFallback: {fallback}\nLatest response time: {elapsed}\nFallback switches: {switches}\nHistory: {requests} responses, average {average:.1f} s":
        "Aktiv: {provider} / {model}\nReserv: {fallback}\nSenaste svarstid: {elapsed}\nByten till reserv: {switches}\nHistorik: {requests} svar, genomsnitt {average:.1f} s",
    "No provider statistics available yet.": "Ingen leverantörsstatistik än.",
    "{key}\n  Requests: {requests} | Successful: {successes} | Errors: {errors} | Success rate: {rate:.0f}%\n  Average: {average:.1f} s | Fallback: {fallbacks}":
        "{key}\n  Anrop: {requests} | Lyckade: {successes} | Fel: {errors} | Andel lyckade: {rate:.0f}%\n  Genomsnitt: {average:.1f} s | Reserv: {fallbacks}",
    "Provider statistics": "Leverantörsstatistik",
    "Reset statistics": "Nollställ statistik",
    "Delete all saved provider statistics?": "Ta bort all sparad leverantörsstatistik?",
    "Provider statistics have been reset.": "Leverantörsstatistiken är nollställd.",
    "Choose workspace": "Välj arbetsyta",
    "Workspace folder does not exist: {path}": "Mappen för arbetsytan finns inte: {path}",
    "Invalid settings": "Ogiltiga inställningar",
    "Could not fetch models": "Kunde inte hämta modeller",
    "Click FETCH MODELS to load provider models": "Klicka på HÄMTA MODELLER för att läsa in leverantörens modeller",
    "Type or select a model for this provider": "Skriv eller välj en modell för leverantören",
    "Connection OK": "Anslutningen fungerar",
    "The demo provider is available.": "Demoleverantören är tillgänglig.",
    "Provider responded and the model exists:\n{model}": "Leverantören svarade och modellen finns:\n{model}",
    "Connection failed": "Anslutningen misslyckades",
    "Language": "Språk",
    "Arqen's language: menus, buttons and texts. Takes effect when Arqen restarts.":
        "Arqens språk: menyer, knappar och texter. Gäller när Arqen startas om.",
    "Restart to change language": "Starta om för att byta språk",
    "The language changes when Arqen restarts. Restart now?": "Språket byts när Arqen startas om. Starta om nu?",
    # Tool catalogue sections (tool_catalog.CATEGORIES)
    "Windows & programs": "Fönster & program",
    "Workspace files": "Filer i arbetsytan",
    "Documents": "Dokument",
    "Web": "Webb",
    "Browser": "Webbläsare",
    "Voice & image": "Röst & bild",
    "Development": "Utveckling",
    "Messages": "Meddelanden",
    "Other": "Övrigt",
    # Connection cards (arqen/connectors)
    "The computer's status, time, resources and processes.": "Datorns status, tid, resurser och processer.",
    "See, focus, start and close programs and windows.": "Se, fokusera, starta och stänga program och fönster.",
    "List, search, read and change files in the workspace.": "Lista, söka, läsa och ändra filer i arbetsytan.",
    "Read PDF, Word and Excel files.": "Läsa PDF-, Word- och Excel-filer.",
    "Search the web, fetch pages, tech news, release notes and weather.": "Söka på webben, hämta sidor, tekniknyheter, release notes och väder.",
    "Control Arqen's own browser: go to, read, click.": "Styra Arqens egen webbläsare: gå till, läsa, klicka.",
    "Read text aloud and create images.": "Läsa upp text och skapa bilder.",
    "Propose things to remember; you approve them.": "Föreslå saker att minnas; du godkänner dem.",
    "Tools without a group of their own.": "Verktyg utan egen grupp.",
    "MCP server: {where}": "MCP-server: {where}",
    "Repos, issues and pull requests. Creating issues requires approval.": "Repon, issues och pull requests. Att skapa issues kräver godkännande.",
    "Personal token": "Personlig token",
    "Create a fine-grained token under GitHub → Settings → Developer settings. Give read access to repos and issues only, plus write access to issues if agents should be able to create them.":
        "Skapa en fine-grained token under GitHub → Settings → Developer settings. Ge bara läsrätt till repon och issues, plus skrivrätt till issues om agenter ska kunna skapa dem.",
    "Read Gmail, Calendar and Drive. Mail drafts and calendar events are created with approval; nothing is sent.":
        "Läsa Gmail, Kalender och Drive. Mejlutkast och kalenderhändelser skapas med godkännande; inget skickas.",
    "Client ID": "Klient-ID",
    "Client secret": "Klienthemlighet",
    "Google Cloud Console → APIs & Services → Credentials → Create an OAuth client ID of type Desktop app.":
        "Google Cloud Console → API:er och tjänster → Inloggningsuppgifter → Skapa OAuth-klient-ID av typen Datorapp (Desktop app).",
    "Send messages to a channel via webhook, e.g. when a task is done.": "Skicka meddelanden till en kanal via webhook, t.ex. när en uppgift är klar.",
    "Webhook address": "Webhook-adress",
    "Channel settings → Integrations → Webhooks → New webhook → Copy URL.": "Kanalinställningar → Integrationer → Webhooks → Ny webhook → Kopiera adress.",
    "Send messages through your own bot, e.g. when a task is done.": "Skicka meddelanden via en egen bot, t.ex. när en uppgift är klar.",
    "Bot token": "Bot-token",
    "Create a bot with @BotFather in Telegram and copy the token.": "Skapa en bot hos @BotFather i Telegram och kopiera token.",
    "Chat ID": "Chatt-id",
    "Write something to the bot in Telegram and press FETCH CHAT ID, or get your id from @userinfobot.":
        "Skriv något till boten i Telegram och tryck HÄMTA CHATT-ID, eller hämta ditt id via @userinfobot.",
    "Bearer token if the server requires one": "Bearer-token om servern kräver det",
    # Chat engine replies (arqen/core/engine.py)
    "Voice mode on.": "Röstläge aktiverat.",
    "Voice mode off.": "Röstläge avstängt.",
    "Voice mode is off. Turn on 🔊 to have text read aloud.": "Röstläge är avstängt. Slå på 🔊 för att använda uppläsning.",
    "I need your confirmation before I run the tool '{name}'.": "Jag behöver din bekräftelse innan jag kör verktyget '{name}'.",
    "Cancelled.": "Avbrutet.",
    "I could not get any further.": "Jag kom inte vidare.",
    "Saved to memory: {fact}": "Jag har sparat i minnet: {fact}",
    "My memory is empty.": "Mitt minne är tomt.",
    "I remember:": "Jag minns:",
    "I have forgotten: {fact}": "Jag har glömt: {fact}",
    "I had not saved: {fact}": "Jag hade inte sparat: {fact}",
    "I need your confirmation before I export the chat to '{path}'.": "Jag behöver din bekräftelse innan jag exporterar chatten till '{path}'.",
    "There is no earlier tool result to summarise.": "Det finns inget tidigare verktygssvar att sammanfatta.",
    "Give a result number, for example: summarize result 3": "Ange ett resultatnummer, exempelvis: sammanfatta resultat 3",
    "That result number is not in the latest search.": "Det resultatnumret finns inte i den senaste sökningen.",
    # Command line (python -m arqen)
    "Configuration error: {error}": "Konfigurationsfel: {error}",
    "Arqen Desktop demo. Type 'quit' to exit.": "Arqen Desktop demo. Skriv 'quit' för att avsluta.",
    "You": "Du",
    "Arqen could not answer: {error}": "Arqen kunde inte svara: {error}",
    # Mobile access (arqen/api/)
    'The title cannot be empty.': 'Titeln får inte vara tom.',
    'The message cannot be empty.': 'Meddelandet får inte vara tomt.',
    'Nothing is waiting for confirmation.': 'Inget väntar på bekräftelse.',
    'Mobile': 'Mobil',
    'Let my phone reach Arqen': 'Låt min telefon nå Arqen',
    'Tailscale (recommended)': 'Tailscale (rekommenderas)',
    'Local network': 'Lokalt nätverk',
    'This computer only': 'Bara den här datorn',
    'Network': 'Nätverk',
    'Port': 'Port',
    'COPY LINK': 'KOPIERA LÄNK',
    'NEW TOKEN': 'NY TOKEN',
    "Scan the code with your phone's camera and add the page to your home screen. The code holds a token that gives full access to Arqen: do not share it. With Tailscale only devices in your own tailnet can connect; install Tailscale on the phone too.": 'Skanna koden med telefonens kamera och lägg sidan på hemskärmen. Koden innehåller en token som ger full åtkomst till Arqen: dela den inte. Med Tailscale kan bara enheter i ditt eget tailnet ansluta; installera Tailscale på telefonen också.',
    'On. Open {url} on your phone.': 'På. Öppna {url} på telefonen.',
    'Could not start: {error}': 'Kunde inte starta: {error}',
    'Off.': 'Av.',
    'Phones signed in with the current token will have to scan the new code. Continue?': 'Telefoner som är inloggade med nuvarande token måste skanna den nya koden. Fortsätta?',
    'Tailscale is not running on this computer.': 'Tailscale körs inte på den här datorn.',
    'This computer is not on a local network.': 'Datorn är inte ansluten till något lokalt nätverk.',
    'Chats': 'Chattar',
    'Approvals': 'Godkännanden',
    'Connect': 'Anslut',
    'Scan the QR code under Settings → Mobile in Arqen on your computer, or paste the token from there.': 'Skanna QR-koden under Inställningar → Mobil i Arqen på datorn, eller klistra in token därifrån.',
    'Token': 'Token',
    'The token was not accepted. Scan the QR code again.': 'Token godtogs inte. Skanna QR-koden igen.',
    'Arqen cannot be reached. Is it running on your computer?': 'Arqen går inte att nå. Är den igång på datorn?',
    'Message Arqen…': 'Skriv till Arqen…',
    'Arqen is thinking…': 'Arqen tänker…',
    'Arqen wants to run {tool}': 'Arqen vill köra {tool}',
    'Approve': 'Godkänn',
    'Reject': 'Avvisa',
    'Approved': 'Godkänt',
    'Rejected': 'Avvisat',
    'Nothing is waiting for you.': 'Inget väntar på dig.',
    'No chats yet. Start one below.': 'Inga chattar än. Starta en nedan.',
    'No tasks yet.': 'Inga uppgifter än.',
    'Back': 'Tillbaka',
    'Result': 'Resultat',
    'Error': 'Fel',
    'Sign out': 'Logga ut',
    'Something went wrong: {error}': 'Något gick fel: {error}',
    'Task': 'Uppgift',
}

# Task, run and event states are stored in English; these are their labels.
_STATUS_SV = {
    "queued": "I KÖ",
    "running": "KÖRS",
    "waiting_approval": "VÄNTAR PÅ GODKÄNNANDE",
    "completed": "KLAR",
    "failed": "MISSLYCKAD",
    "cancelled": "AVBRUTEN",
    "created": "SKAPAD",
    "started": "STARTAD",
    "approval_requested": "GODKÄNNANDE BEGÄRT",
    "approval_approved": "GODKÄND",
    "approval_rejected": "AVVISAD",
}


# When ``count`` is 1 these replace the plural text, per language.
_ONE: dict[str, dict[str, str]] = {
    "en": {
        "All {count} tools": "{count} tool",
        "Tool costs in this log: {total} over {count} paid calls": "Tool costs in this log: {total} over {count} paid call",
        "{count} connections need to be signed in again.": "{count} connection needs to be signed in again.",
        "Works: {count} tools ({read_only} read-only).": "Works: {count} tool ({read_only} read-only).",
        "{count} steps  ·  multi-agent pipeline": "{count} step  ·  multi-agent pipeline",
        "{count} tasks": "{count} task",
        "{runtime} runtime  ·  {count} tools": "{runtime} runtime  ·  {count} tool",
        "Arqen found {count} new suggestions. Review them below.": "Arqen found {count} new suggestion. Review it below.",
        "{count} require approval": "{count} requires approval",
        "{count} tools  ·  {approval} require approval": "{count} tool  ·  {approval} require approval",
        "{count} tools": "{count} tool",
    },
    "sv": {
        "All {count} tools": "{count} verktyg",
        "{count} connections need to be signed in again.": "{count} anslutning behöver loggas in igen.",
        "{count} tasks": "{count} uppgift",
        "Arqen found {count} new suggestions. Review them below.": "Arqen hittade {count} nytt förslag. Granska det nedan.",
    },
}


def tr(text: str, **values) -> str:
    """The UI text for ``text`` in the current language, with ``values`` filled in."""
    if values.get("count") == 1 and text in _ONE.get(LANGUAGE, {}):
        template = _ONE[LANGUAGE][text]
    else:
        template = _SV.get(text, text) if LANGUAGE == "sv" else text
    return template.format(**values) if values else template


def status_label(status: str) -> str:
    """A task, run or event state as the user reads it."""
    if LANGUAGE == "sv" and status in _STATUS_SV:
        return _STATUS_SV[status]
    return status.upper().replace("_", " ")


def tr_status(text: str) -> str:
    """Translate a ``PART // PART`` status line part by part."""
    return " // ".join(tr(part) for part in text.split(" // "))
